### ISSUE TITLE
About the caption.csv

### ISSUE THREAD

**Issue by xuanxu92** [masatsuneki/histopathology-image-caption#1]
Hi, this is a great work for wsi. I download the captions.csv and patches_captions. I find that the scan_id like cjmbvjife000f01qh6xxwinst in captions.csv and the patch name like0a11cea22a1040ae8fa43a913af092c5_0a7cb6.jpg. Could you please tell me how I can find the caption corresponding patch? I don't find the corresponding patch for 'cjmbvjife000f01qh6xxwinst' scan_id. Thanks in advance.

**Comment by masatsuneki** [comment]
Thanks for your interest. Please refer to https://github.com/masatsuneki/histopathology-image-caption/blob/main/captions.csv which has the matching names. There was a mistake in the file uploaded to zenodo, and it was corrected with this version https://zenodo.org/record/6550925

**Comment by xuanxu92** [comment]
Thanks for your reply. For the correct captions.csv, I find there are around 1000 ids. So each id (such as 0a11cea22a1040ae8fa43a913af092c5) is corresponding to a list of patches (0a11cea22a1040ae8fa43a913af092c5_0a7cb6.jpg, 0a11cea22a1040ae8fa43a913af092c5_0a569b.jpg,...), right? For these patches, they share the same text, right?

**Comment by masatsuneki** [comment]
Thank you.
> So each id (such as 0a11cea22a1040ae8fa43a913af092c5) is corresponding to a list of patches (0a11cea22a1040ae8fa43a913af092c5_0a7cb6.jpg, 0a11cea22a1040ae8fa43a913af092c5_0a569b.jpg,...), right?

Response: Yes.

> For these patches, they share the same text, right?

Response: Yes.

**Comment by xuanxu92** [comment]
Thanks so much!
