### ISSUE TITLE
about whole slide image

### ISSUE THREAD

**Issue by xuanxu92** [masatsuneki/histopathology-image-caption#2]
Hi, this is a great work! Could you please tell me whether there are corresponding whole slide images for patches. Like patch (0a83e3670e214a6f88a3a79e5200bfa7_000bbb.jpg,0a83e3670e214a6f88a3a79e5200bfa7_0d201e.jpg,...) and their corresponding wsi should be0a83e3670e214a6f88a3a79e5200bfa7, each patch share the same id is corresponding to one whole slide image, right? Could you please tell me whether there are corresponding whole slide images for patches? Thanks!

**Comment by masatsuneki** [comment]
@xuanxu92 

Thank you. All patches starting with the same id originate from the same WSI. Unfortunately, we can't provide the original WSIs.

**Comment by xuanxu92** [comment]
Thanks!
