### ISSUE TITLE
About the class of a particular image in the dataset

### ISSUE THREAD

**Issue by DriveNU** [masatsuneki/histopathology-image-caption#4]
Hi, thanks for this great dataset. I found that in the csv file, the image 'e1d7db7669914760b07815837733e524' on row 44 have 2 classes 'Poorly differentiated adenocarcinoma, solid type. Moderately differentiated tubular adenocarcinoma.' assigned to it. Is this supposed to be correct?

**Comment by masatsuneki** [comment]
Thank you. Yes, the image "e1d7db7669914760b07815837733e524" was generated from a WSI (whole slide image). The WSI includes two classes of adenocarcinoma: one is poorly differentiated adenocarcinoma and the other is moderately differentiated tubular adenocarcinoma. Therefore, the generated image has two classes.

**Comment by DriveNU** [comment]
Is it possible for you to provide additional information on which patches are labelled as poorly differentiated adenocarcinoma and which patches are labelled as moderately differentiated tubular adenocarcinoma for this WSI?

**Comment by masatsuneki** [comment]
Sorry, there are so many patches including in this WSI. So it is very hard for me (very timeconsuming) to do this at this point. I feel very sorry.

**Comment by DriveNU** [comment]
No problem. There is another small question that I would like to confirm: all the 262,777 patches are cancerous tissue regions (of their corresponding WSI labelled subtype) and none are healthy tissue region? This is because I would like to use the dataset for patch subtype classification.

**Comment by masatsuneki** [comment]
Yes, the 262,777 patches were extracted from the cancerous tissue WSIs of their corresponding WSI labelled subtype.

**Comment by DriveNU** [comment]
Okay thanks for your help!
