### ISSUE TITLE
Magnification of extracted patches?

### ISSUE THREAD

**Issue by fedshyvana** [masatsuneki/histopathology-image-caption#5]
Dear authors, thank you for your work and for releasing this cool dataset! I am curious - in the paper it was mentioned you experimented with both 10x and 20x but I don't believe this information is indicated in the dataset I downloaded. Could you please let me know if the patches released are at 10x or 20x? Thanks!

**Comment by masatsuneki** [comment]
@fedshyvana 
Thank you. They are at x20.
